# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fafa417d2d454381d20bb9c78c605a08b59b9f44e7e22ddf07e2cf77529f395f8b77b9643b96f9d8fd19d05ae78257d219b79be1054a22a5244183e2919ac11b

test:
  secret_key_base: f070cf530dbc56beb411404d134b81945bfdf566c90e89513ef0ebb6e4532fa7d25c653029e1423cf197eb5457a86d3fd975d2cbe349aa7faf074708d1c1e6c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
